Move to mkdocs
esnet-security/SCRAM pull request #84
Opened 2024-11-18 18:43 UTC by grigorescu

Not 100% sure the GitHub Pages action works.

2024-11-20 05:59 UTC, samoehlert requested changes

2024-11-20 05:59 UTC, samoehlert commented on docs/conf.py
This file seems to reference sphinx a lot. Are we keeping sphinx as well for now?

2024-11-20 05:59 UTC, samoehlert commented on mkdocs.yml
Can we remove the commented out bits at the end?

2024-11-21 13:49 UTC, grigorescu commented on docs/conf.py
This file shouldn't REALLY be part of this PR, but I did want to get this change into the version history, in case we ever need to go back to Sphinx.

2024-11-21 13:50 UTC, grigorescu commented on docs/conf.py
I also want to see that this actually works with GitHub Pages before going back and ripping out the Sphinx stuff.

2024-11-21 13:50 UTC, grigorescu commented on mkdocs.yml
These should probably be TODOs. I'd like to get those added, but haven't figured out the right packages for them.

Keep them or remove them?

2024-11-21 14:33 UTC, grigorescu commented on docs/conf.py
Actually, nevermind. It's in the history already.

2024-11-21 14:36 UTC, grigorescu commented on mkdocs.yml
Nevermind.

2024-11-21 15:04 UTC, samoehlert submitted a review, later dismissed

2024-11-22 20:50 UTC, samoehlert approved these changes

2024-11-23 01:02 UTC, merged